# Site settings
title: GitHub Wiki-like Jekyll Theme
name: GitHub Wiki-like Jekyll Theme
description: A simple Jekyll theme inspired by GitHub Wikis.
email: il@livius.net

destination: _site
exclude:
  - README.md

# Used in sitemap.xml
url: "http://ilg-ul.github.io" # the base hostname & protocol for your site

# The subpath of your site, e.g. /blog (note the leading slash and the
# absence of a trailing slash).
baseurl: "/github-jekyll-theme"

timezone: UTC
encoding: utf-8

# Default permalink used for posts
permalink: /:year/:month/:day/:title/

# Build settings
markdown: redcarpet

redcarpet:
  extensions: []

paginate: 2
paginate_path: "/blog/page:num/"

gems:
  - jekyll-last-modified-at
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

# Custom defs
github-username:  ilg-ul
github-project-name: ilg-ul/github-jekyll-theme

google-analytics-id: UA-000000-01

custom-footer-content: content/site-custom-footer.markdown
copyright-message: "© 2015 Liviu Ionescu"
